all: True
quiet: False
disable-version-string: False
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
dir: mocks/.
outpkg: mocks
packages:
  pixelix/entity:
  pixelix/pkg/logger:
