all: True
quiet: False
keeptree: False
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}"
outpkg: mocks
dir: ./entity/mocks
packages:
  cryptoChallenges/entity:
  cryptoChallenges/pkg/logger:

