version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: crypto-challenges-sqlx
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cryptoChallenges
      MYSQL_DATABASE: cryptoChallenges
      MYSQL_USER: cryptoChallenges
      MYSQL_PASSWORD: cryptoChallenges
    ports:
      - "3306:3306"