version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: blipix-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blipix
      MYSQL_DATABASE: blipix
      MYSQL_USER: blipix
      MYSQL_PASSWORD: blipix
    ports:
      - "3306:3306"
    volumes:
      - ./docker:/etc/mysql/conf.d