// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "pixelix/entity"

	mock "github.com/stretchr/testify/mock"
)

// ChallengeHistoryService is an autogenerated mock type for the ChallengeHistoryService type
type ChallengeHistoryService struct {
	mock.Mock
}

type ChallengeHistoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *ChallengeHistoryService) EXPECT() *ChallengeHistoryService_Expecter {
	return &ChallengeHistoryService_Expecter{mock: &_m.Mock}
}

// CreateMissionHistory provides a mock function with given fields: ctx, req
func (_m *ChallengeHistoryService) CreateMissionHistory(ctx context.Context, req entity.CreateMissionHistoryRequest) (*entity.CreateMissionHistoryResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *entity.CreateMissionHistoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateMissionHistoryRequest) (*entity.CreateMissionHistoryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateMissionHistoryRequest) *entity.CreateMissionHistoryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CreateMissionHistoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateMissionHistoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChallengeHistoryService_CreateMissionHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMissionHistory'
type ChallengeHistoryService_CreateMissionHistory_Call struct {
	*mock.Call
}

// CreateMissionHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - req entity.CreateMissionHistoryRequest
func (_e *ChallengeHistoryService_Expecter) CreateMissionHistory(ctx interface{}, req interface{}) *ChallengeHistoryService_CreateMissionHistory_Call {
	return &ChallengeHistoryService_CreateMissionHistory_Call{Call: _e.mock.On("CreateMissionHistory", ctx, req)}
}

func (_c *ChallengeHistoryService_CreateMissionHistory_Call) Run(run func(ctx context.Context, req entity.CreateMissionHistoryRequest)) *ChallengeHistoryService_CreateMissionHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CreateMissionHistoryRequest))
	})
	return _c
}

func (_c *ChallengeHistoryService_CreateMissionHistory_Call) Return(_a0 *entity.CreateMissionHistoryResponse, _a1 error) *ChallengeHistoryService_CreateMissionHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChallengeHistoryService_CreateMissionHistory_Call) RunAndReturn(run func(context.Context, entity.CreateMissionHistoryRequest) (*entity.CreateMissionHistoryResponse, error)) *ChallengeHistoryService_CreateMissionHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListMultiChallengeHistories provides a mock function with given fields: ctx, req
func (_m *ChallengeHistoryService) ListMultiChallengeHistories(ctx context.Context, req entity.ListMultiChallengeHistoriesRequest) (*entity.ListMultiChallengeHistoriesResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *entity.ListMultiChallengeHistoriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ListMultiChallengeHistoriesRequest) (*entity.ListMultiChallengeHistoriesResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ListMultiChallengeHistoriesRequest) *entity.ListMultiChallengeHistoriesResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ListMultiChallengeHistoriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ListMultiChallengeHistoriesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChallengeHistoryService_ListMultiChallengeHistories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMultiChallengeHistories'
type ChallengeHistoryService_ListMultiChallengeHistories_Call struct {
	*mock.Call
}

// ListMultiChallengeHistories is a helper method to define mock.On call
//   - ctx context.Context
//   - req entity.ListMultiChallengeHistoriesRequest
func (_e *ChallengeHistoryService_Expecter) ListMultiChallengeHistories(ctx interface{}, req interface{}) *ChallengeHistoryService_ListMultiChallengeHistories_Call {
	return &ChallengeHistoryService_ListMultiChallengeHistories_Call{Call: _e.mock.On("ListMultiChallengeHistories", ctx, req)}
}

func (_c *ChallengeHistoryService_ListMultiChallengeHistories_Call) Run(run func(ctx context.Context, req entity.ListMultiChallengeHistoriesRequest)) *ChallengeHistoryService_ListMultiChallengeHistories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ListMultiChallengeHistoriesRequest))
	})
	return _c
}

func (_c *ChallengeHistoryService_ListMultiChallengeHistories_Call) Return(_a0 *entity.ListMultiChallengeHistoriesResponse, _a1 error) *ChallengeHistoryService_ListMultiChallengeHistories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChallengeHistoryService_ListMultiChallengeHistories_Call) RunAndReturn(run func(context.Context, entity.ListMultiChallengeHistoriesRequest) (*entity.ListMultiChallengeHistoriesResponse, error)) *ChallengeHistoryService_ListMultiChallengeHistories_Call {
	_c.Call.Return(run)
	return _c
}

// NewChallengeHistoryService creates a new instance of ChallengeHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChallengeHistoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChallengeHistoryService {
	mock := &ChallengeHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
