// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChallengeRepository is an autogenerated mock type for the ChallengeRepository type
type ChallengeRepository struct {
	mock.Mock
}

type ChallengeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ChallengeRepository) EXPECT() *ChallengeRepository_Expecter {
	return &ChallengeRepository_Expecter{mock: &_m.Mock}
}

// NewChallengeRepository creates a new instance of ChallengeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChallengeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChallengeRepository {
	mock := &ChallengeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
