// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "pixelix/entity"

	mock "github.com/stretchr/testify/mock"
)

// ChallengeParticipantRepository is an autogenerated mock type for the ChallengeParticipantRepository type
type ChallengeParticipantRepository struct {
	mock.Mock
}

type ChallengeParticipantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ChallengeParticipantRepository) EXPECT() *ChallengeParticipantRepository_Expecter {
	return &ChallengeParticipantRepository_Expecter{mock: &_m.Mock}
}

// CreateChallengeParticipant provides a mock function with given fields: ctx, participant
func (_m *ChallengeParticipantRepository) CreateChallengeParticipant(ctx context.Context, participant *entity.ChallengeParticipant) (*entity.ChallengeParticipant, error) {
	ret := _m.Called(ctx, participant)

	var r0 *entity.ChallengeParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ChallengeParticipant) (*entity.ChallengeParticipant, error)); ok {
		return rf(ctx, participant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ChallengeParticipant) *entity.ChallengeParticipant); ok {
		r0 = rf(ctx, participant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ChallengeParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.ChallengeParticipant) error); ok {
		r1 = rf(ctx, participant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChallengeParticipantRepository_CreateChallengeParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChallengeParticipant'
type ChallengeParticipantRepository_CreateChallengeParticipant_Call struct {
	*mock.Call
}

// CreateChallengeParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - participant *entity.ChallengeParticipant
func (_e *ChallengeParticipantRepository_Expecter) CreateChallengeParticipant(ctx interface{}, participant interface{}) *ChallengeParticipantRepository_CreateChallengeParticipant_Call {
	return &ChallengeParticipantRepository_CreateChallengeParticipant_Call{Call: _e.mock.On("CreateChallengeParticipant", ctx, participant)}
}

func (_c *ChallengeParticipantRepository_CreateChallengeParticipant_Call) Run(run func(ctx context.Context, participant *entity.ChallengeParticipant)) *ChallengeParticipantRepository_CreateChallengeParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ChallengeParticipant))
	})
	return _c
}

func (_c *ChallengeParticipantRepository_CreateChallengeParticipant_Call) Return(_a0 *entity.ChallengeParticipant, _a1 error) *ChallengeParticipantRepository_CreateChallengeParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChallengeParticipantRepository_CreateChallengeParticipant_Call) RunAndReturn(run func(context.Context, *entity.ChallengeParticipant) (*entity.ChallengeParticipant, error)) *ChallengeParticipantRepository_CreateChallengeParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// ListMissionParticipants provides a mock function with given fields: ctx, missionID
func (_m *ChallengeParticipantRepository) ListMissionParticipants(ctx context.Context, missionID uint) ([]entity.ChallengeParticipant, error) {
	ret := _m.Called(ctx, missionID)

	var r0 []entity.ChallengeParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entity.ChallengeParticipant, error)); ok {
		return rf(ctx, missionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entity.ChallengeParticipant); ok {
		r0 = rf(ctx, missionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ChallengeParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, missionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChallengeParticipantRepository_ListMissionParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMissionParticipants'
type ChallengeParticipantRepository_ListMissionParticipants_Call struct {
	*mock.Call
}

// ListMissionParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - missionID uint
func (_e *ChallengeParticipantRepository_Expecter) ListMissionParticipants(ctx interface{}, missionID interface{}) *ChallengeParticipantRepository_ListMissionParticipants_Call {
	return &ChallengeParticipantRepository_ListMissionParticipants_Call{Call: _e.mock.On("ListMissionParticipants", ctx, missionID)}
}

func (_c *ChallengeParticipantRepository_ListMissionParticipants_Call) Run(run func(ctx context.Context, missionID uint)) *ChallengeParticipantRepository_ListMissionParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *ChallengeParticipantRepository_ListMissionParticipants_Call) Return(_a0 []entity.ChallengeParticipant, _a1 error) *ChallengeParticipantRepository_ListMissionParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChallengeParticipantRepository_ListMissionParticipants_Call) RunAndReturn(run func(context.Context, uint) ([]entity.ChallengeParticipant, error)) *ChallengeParticipantRepository_ListMissionParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// NewChallengeParticipantRepository creates a new instance of ChallengeParticipantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChallengeParticipantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChallengeParticipantRepository {
	mock := &ChallengeParticipantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
