// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ChallengeHistoryController is an autogenerated mock type for the ChallengeHistoryController type
type ChallengeHistoryController struct {
	mock.Mock
}

type ChallengeHistoryController_Expecter struct {
	mock *mock.Mock
}

func (_m *ChallengeHistoryController) EXPECT() *ChallengeHistoryController_Expecter {
	return &ChallengeHistoryController_Expecter{mock: &_m.Mock}
}

// CreateMissionHistory provides a mock function with given fields: c
func (_m *ChallengeHistoryController) CreateMissionHistory(c *gin.Context) {
	_m.Called(c)
}

// ChallengeHistoryController_CreateMissionHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMissionHistory'
type ChallengeHistoryController_CreateMissionHistory_Call struct {
	*mock.Call
}

// CreateMissionHistory is a helper method to define mock.On call
//   - c *gin.Context
func (_e *ChallengeHistoryController_Expecter) CreateMissionHistory(c interface{}) *ChallengeHistoryController_CreateMissionHistory_Call {
	return &ChallengeHistoryController_CreateMissionHistory_Call{Call: _e.mock.On("CreateMissionHistory", c)}
}

func (_c *ChallengeHistoryController_CreateMissionHistory_Call) Run(run func(c *gin.Context)) *ChallengeHistoryController_CreateMissionHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *ChallengeHistoryController_CreateMissionHistory_Call) Return() *ChallengeHistoryController_CreateMissionHistory_Call {
	_c.Call.Return()
	return _c
}

func (_c *ChallengeHistoryController_CreateMissionHistory_Call) RunAndReturn(run func(*gin.Context)) *ChallengeHistoryController_CreateMissionHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListMultiModeMissionHistories provides a mock function with given fields: c
func (_m *ChallengeHistoryController) ListMultiModeMissionHistories(c *gin.Context) {
	_m.Called(c)
}

// ChallengeHistoryController_ListMultiModeMissionHistories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMultiModeMissionHistories'
type ChallengeHistoryController_ListMultiModeMissionHistories_Call struct {
	*mock.Call
}

// ListMultiModeMissionHistories is a helper method to define mock.On call
//   - c *gin.Context
func (_e *ChallengeHistoryController_Expecter) ListMultiModeMissionHistories(c interface{}) *ChallengeHistoryController_ListMultiModeMissionHistories_Call {
	return &ChallengeHistoryController_ListMultiModeMissionHistories_Call{Call: _e.mock.On("ListMultiModeMissionHistories", c)}
}

func (_c *ChallengeHistoryController_ListMultiModeMissionHistories_Call) Run(run func(c *gin.Context)) *ChallengeHistoryController_ListMultiModeMissionHistories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *ChallengeHistoryController_ListMultiModeMissionHistories_Call) Return() *ChallengeHistoryController_ListMultiModeMissionHistories_Call {
	_c.Call.Return()
	return _c
}

func (_c *ChallengeHistoryController_ListMultiModeMissionHistories_Call) RunAndReturn(run func(*gin.Context)) *ChallengeHistoryController_ListMultiModeMissionHistories_Call {
	_c.Call.Return(run)
	return _c
}

// NewChallengeHistoryController creates a new instance of ChallengeHistoryController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChallengeHistoryController(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChallengeHistoryController {
	mock := &ChallengeHistoryController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
