// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChallengeParticipantController is an autogenerated mock type for the ChallengeParticipantController type
type ChallengeParticipantController struct {
	mock.Mock
}

type ChallengeParticipantController_Expecter struct {
	mock *mock.Mock
}

func (_m *ChallengeParticipantController) EXPECT() *ChallengeParticipantController_Expecter {
	return &ChallengeParticipantController_Expecter{mock: &_m.Mock}
}

// NewChallengeParticipantController creates a new instance of ChallengeParticipantController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChallengeParticipantController(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChallengeParticipantController {
	mock := &ChallengeParticipantController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
