// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// GroupChallengeController is an autogenerated mock type for the GroupChallengeController type
type GroupChallengeController struct {
	mock.Mock
}

type GroupChallengeController_Expecter struct {
	mock *mock.Mock
}

func (_m *GroupChallengeController) EXPECT() *GroupChallengeController_Expecter {
	return &GroupChallengeController_Expecter{mock: &_m.Mock}
}

// CreateGroupChallenge provides a mock function with given fields: c
func (_m *GroupChallengeController) CreateGroupChallenge(c *gin.Context) {
	_m.Called(c)
}

// GroupChallengeController_CreateGroupChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupChallenge'
type GroupChallengeController_CreateGroupChallenge_Call struct {
	*mock.Call
}

// CreateGroupChallenge is a helper method to define mock.On call
//   - c *gin.Context
func (_e *GroupChallengeController_Expecter) CreateGroupChallenge(c interface{}) *GroupChallengeController_CreateGroupChallenge_Call {
	return &GroupChallengeController_CreateGroupChallenge_Call{Call: _e.mock.On("CreateGroupChallenge", c)}
}

func (_c *GroupChallengeController_CreateGroupChallenge_Call) Run(run func(c *gin.Context)) *GroupChallengeController_CreateGroupChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *GroupChallengeController_CreateGroupChallenge_Call) Return() *GroupChallengeController_CreateGroupChallenge_Call {
	_c.Call.Return()
	return _c
}

func (_c *GroupChallengeController_CreateGroupChallenge_Call) RunAndReturn(run func(*gin.Context)) *GroupChallengeController_CreateGroupChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// NewGroupChallengeController creates a new instance of GroupChallengeController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupChallengeController(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupChallengeController {
	mock := &GroupChallengeController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
