// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GroupChallengeRepository is an autogenerated mock type for the GroupChallengeRepository type
type GroupChallengeRepository struct {
	mock.Mock
}

type GroupChallengeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GroupChallengeRepository) EXPECT() *GroupChallengeRepository_Expecter {
	return &GroupChallengeRepository_Expecter{mock: &_m.Mock}
}

// NewGroupChallengeRepository creates a new instance of GroupChallengeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupChallengeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupChallengeRepository {
	mock := &GroupChallengeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
