// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MissionHistoryRepository is an autogenerated mock type for the MissionHistoryRepository type
type MissionHistoryRepository struct {
	mock.Mock
}

type MissionHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MissionHistoryRepository) EXPECT() *MissionHistoryRepository_Expecter {
	return &MissionHistoryRepository_Expecter{mock: &_m.Mock}
}

// NewMissionHistoryRepository creates a new instance of MissionHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMissionHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MissionHistoryRepository {
	mock := &MissionHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
