// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MissionRepository is an autogenerated mock type for the MissionRepository type
type MissionRepository struct {
	mock.Mock
}

type MissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MissionRepository) EXPECT() *MissionRepository_Expecter {
	return &MissionRepository_Expecter{mock: &_m.Mock}
}

// NewMissionRepository creates a new instance of MissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MissionRepository {
	mock := &MissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
