// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MissionParticipantService is an autogenerated mock type for the MissionParticipantService type
type MissionParticipantService struct {
	mock.Mock
}

type MissionParticipantService_Expecter struct {
	mock *mock.Mock
}

func (_m *MissionParticipantService) EXPECT() *MissionParticipantService_Expecter {
	return &MissionParticipantService_Expecter{mock: &_m.Mock}
}

// NewMissionParticipantService creates a new instance of MissionParticipantService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMissionParticipantService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MissionParticipantService {
	mock := &MissionParticipantService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
