// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MissionParticipantController is an autogenerated mock type for the MissionParticipantController type
type MissionParticipantController struct {
	mock.Mock
}

type MissionParticipantController_Expecter struct {
	mock *mock.Mock
}

func (_m *MissionParticipantController) EXPECT() *MissionParticipantController_Expecter {
	return &MissionParticipantController_Expecter{mock: &_m.Mock}
}

// NewMissionParticipantController creates a new instance of MissionParticipantController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMissionParticipantController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MissionParticipantController {
	mock := &MissionParticipantController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
