// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "pixelix/dto"

	mock "github.com/stretchr/testify/mock"
)

// MissionService is an autogenerated mock type for the MissionService type
type MissionService struct {
	mock.Mock
}

type MissionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MissionService) EXPECT() *MissionService_Expecter {
	return &MissionService_Expecter{mock: &_m.Mock}
}

// CreateMission provides a mock function with given fields: ctx, req
func (_m *MissionService) CreateMission(ctx context.Context, req dto.CreateMissionRequest) (dto.CreateMissionResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 dto.CreateMissionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateMissionRequest) (dto.CreateMissionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateMissionRequest) dto.CreateMissionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CreateMissionResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateMissionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MissionService_CreateMission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMission'
type MissionService_CreateMission_Call struct {
	*mock.Call
}

// CreateMission is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateMissionRequest
func (_e *MissionService_Expecter) CreateMission(ctx interface{}, req interface{}) *MissionService_CreateMission_Call {
	return &MissionService_CreateMission_Call{Call: _e.mock.On("CreateMission", ctx, req)}
}

func (_c *MissionService_CreateMission_Call) Run(run func(ctx context.Context, req dto.CreateMissionRequest)) *MissionService_CreateMission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateMissionRequest))
	})
	return _c
}

func (_c *MissionService_CreateMission_Call) Return(_a0 dto.CreateMissionResponse, _a1 error) *MissionService_CreateMission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MissionService_CreateMission_Call) RunAndReturn(run func(context.Context, dto.CreateMissionRequest) (dto.CreateMissionResponse, error)) *MissionService_CreateMission_Call {
	_c.Call.Return(run)
	return _c
}

// NewMissionService creates a new instance of MissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MissionService {
	mock := &MissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
