// ServiceCode generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SingleModeService is an autogenerated mock type for the SingleModeService type
type SingleModeService struct {
	mock.Mock
}

type SingleModeService_Expecter struct {
	mock *mock.Mock
}

func (_m *SingleModeService) EXPECT() *SingleModeService_Expecter {
	return &SingleModeService_Expecter{mock: &_m.Mock}
}

// CreateSingleModeMissionHistories provides a mock function with given fields: ctx
func (_m *SingleModeService) CreateSingleModeMissionHistories(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SingleModeService_CreateSingleModeMissionHistories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSingleModeMissionHistories'
type SingleModeService_CreateSingleModeMissionHistories_Call struct {
	*mock.Call
}

// CreateSingleModeMissionHistories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SingleModeService_Expecter) CreateSingleModeMissionHistories(ctx interface{}) *SingleModeService_CreateSingleModeMissionHistories_Call {
	return &SingleModeService_CreateSingleModeMissionHistories_Call{Call: _e.mock.On("CreateSingleModeMissionHistories", ctx)}
}

func (_c *SingleModeService_CreateSingleModeMissionHistories_Call) Run(run func(ctx context.Context)) *SingleModeService_CreateSingleModeMissionHistories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SingleModeService_CreateSingleModeMissionHistories_Call) Return(_a0 error) *SingleModeService_CreateSingleModeMissionHistories_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SingleModeService_CreateSingleModeMissionHistories_Call) RunAndReturn(run func(context.Context) error) *SingleModeService_CreateSingleModeMissionHistories_Call {
	_c.Call.Return(run)
	return _c
}

// NewSingleModeService creates a new instance of SingleModeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSingleModeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SingleModeService {
	mock := &SingleModeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
