// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UserController is an autogenerated mock type for the UserController type
type UserController struct {
	mock.Mock
}

type UserController_Expecter struct {
	mock *mock.Mock
}

func (_m *UserController) EXPECT() *UserController_Expecter {
	return &UserController_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx
func (_m *UserController) CreateUser(ctx *gin.Context) {
	_m.Called(ctx)
}

// UserController_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserController_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *UserController_Expecter) CreateUser(ctx interface{}) *UserController_CreateUser_Call {
	return &UserController_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx)}
}

func (_c *UserController_CreateUser_Call) Run(run func(ctx *gin.Context)) *UserController_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *UserController_CreateUser_Call) Return() *UserController_CreateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserController_CreateUser_Call) RunAndReturn(run func(*gin.Context)) *UserController_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx
func (_m *UserController) GetUser(ctx *gin.Context) {
	_m.Called(ctx)
}

// UserController_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserController_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *UserController_Expecter) GetUser(ctx interface{}) *UserController_GetUser_Call {
	return &UserController_GetUser_Call{Call: _e.mock.On("GetUser", ctx)}
}

func (_c *UserController_GetUser_Call) Run(run func(ctx *gin.Context)) *UserController_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *UserController_GetUser_Call) Return() *UserController_GetUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserController_GetUser_Call) RunAndReturn(run func(*gin.Context)) *UserController_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUserController interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserController creates a new instance of UserController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserController(t mockConstructorTestingTNewUserController) *UserController {
	mock := &UserController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
