// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "cryptoChallenges/dto"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UserService) CreateUser(ctx context.Context, user dto.CreateUserRequest) (dto.CreateUserDTOResponse, error) {
	ret := _m.Called(ctx, user)

	var r0 dto.CreateUserDTOResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserRequest) (dto.CreateUserDTOResponse, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserRequest) dto.CreateUserDTOResponse); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(dto.CreateUserDTOResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateUserRequest) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user dto.CreateUserRequest
func (_e *UserService_Expecter) CreateUser(ctx interface{}, user interface{}) *UserService_CreateUser_Call {
	return &UserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *UserService_CreateUser_Call) Run(run func(ctx context.Context, user dto.CreateUserRequest)) *UserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateUserRequest))
	})
	return _c
}

func (_c *UserService_CreateUser_Call) Return(_a0 dto.CreateUserDTOResponse, _a1 error) *UserService_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_CreateUser_Call) RunAndReturn(run func(context.Context, dto.CreateUserRequest) (dto.CreateUserDTOResponse, error)) *UserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReadUser provides a mock function with given fields: ctx
func (_m *UserService) ReadUser(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_ReadUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadUser'
type UserService_ReadUser_Call struct {
	*mock.Call
}

// ReadUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserService_Expecter) ReadUser(ctx interface{}) *UserService_ReadUser_Call {
	return &UserService_ReadUser_Call{Call: _e.mock.On("ReadUser", ctx)}
}

func (_c *UserService_ReadUser_Call) Run(run func(ctx context.Context)) *UserService_ReadUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserService_ReadUser_Call) Return(_a0 string, _a1 error) *UserService_ReadUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_ReadUser_Call) RunAndReturn(run func(context.Context) (string, error)) *UserService_ReadUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
