// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UserController is an autogenerated mock type for the UserController type
type UserController struct {
	mock.Mock
}

type UserController_Expecter struct {
	mock *mock.Mock
}

func (_m *UserController) EXPECT() *UserController_Expecter {
	return &UserController_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function with given fields: c
func (_m *UserController) DeleteUser(c *gin.Context) {
	_m.Called(c)
}

// UserController_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserController_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *UserController_Expecter) DeleteUser(c interface{}) *UserController_DeleteUser_Call {
	return &UserController_DeleteUser_Call{Call: _e.mock.On("DeleteUser", c)}
}

func (_c *UserController_DeleteUser_Call) Run(run func(c *gin.Context)) *UserController_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *UserController_DeleteUser_Call) Return() *UserController_DeleteUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserController_DeleteUser_Call) RunAndReturn(run func(*gin.Context)) *UserController_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// OAuthLoginUser provides a mock function with given fields: c
func (_m *UserController) OAuthLoginUser(c *gin.Context) {
	_m.Called(c)
}

// UserController_OAuthLoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OAuthLoginUser'
type UserController_OAuthLoginUser_Call struct {
	*mock.Call
}

// OAuthLoginUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *UserController_Expecter) OAuthLoginUser(c interface{}) *UserController_OAuthLoginUser_Call {
	return &UserController_OAuthLoginUser_Call{Call: _e.mock.On("OAuthLoginUser", c)}
}

func (_c *UserController_OAuthLoginUser_Call) Run(run func(c *gin.Context)) *UserController_OAuthLoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *UserController_OAuthLoginUser_Call) Return() *UserController_OAuthLoginUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserController_OAuthLoginUser_Call) RunAndReturn(run func(*gin.Context)) *UserController_OAuthLoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReadUser provides a mock function with given fields: c
func (_m *UserController) ReadUser(c *gin.Context) {
	_m.Called(c)
}

// UserController_ReadUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadUser'
type UserController_ReadUser_Call struct {
	*mock.Call
}

// ReadUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *UserController_Expecter) ReadUser(c interface{}) *UserController_ReadUser_Call {
	return &UserController_ReadUser_Call{Call: _e.mock.On("ReadUser", c)}
}

func (_c *UserController_ReadUser_Call) Run(run func(c *gin.Context)) *UserController_ReadUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *UserController_ReadUser_Call) Return() *UserController_ReadUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserController_ReadUser_Call) RunAndReturn(run func(*gin.Context)) *UserController_ReadUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: c
func (_m *UserController) UpdateUser(c *gin.Context) {
	_m.Called(c)
}

// UserController_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type UserController_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *UserController_Expecter) UpdateUser(c interface{}) *UserController_UpdateUser_Call {
	return &UserController_UpdateUser_Call{Call: _e.mock.On("UpdateUser", c)}
}

func (_c *UserController_UpdateUser_Call) Run(run func(c *gin.Context)) *UserController_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *UserController_UpdateUser_Call) Return() *UserController_UpdateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserController_UpdateUser_Call) RunAndReturn(run func(*gin.Context)) *UserController_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserController creates a new instance of UserController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserController(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserController {
	mock := &UserController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
