app:
  name: 'cryptoChallenges'
  version: '0.0.1'

http:
  port: ':3000'

logger:
  log_level: 'debug'

mysql:
  host: 'localhost'
  port: 3306
  user: 'cryptoChallenges'
  dbName: 'cryptoChallenges'
  password: 'cryptoChallenges'